[tool.poetry]
name = "kodlandpygame"
version = "0.1.0"
description = ""
authors = ["David Córdoba <daviidco@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pygame = "^2.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
